apiVersion: apps/v1
kind: Deployment
metadata:
  name: visacards-api
spec:
  selector:
    matchLabels:
      app: visacards-api
  replicas: 1
  template:
    metadata:
      labels:
        app: visacards-api
    spec:
      containers:
        - name: visacards-api
          image: afonso13/visacards-api:latest
          ports:
            - name: liveness-port
              containerPort: 8080
              hostPort: 8080