DROP TABLE IF EXISTS VISA_CARD;
CREATE TABLE VISA_CARD(
	ID BIGINT PRIMARY KEY,
	CARD_NUMBER VARCHAR(17),
	ADDRESS VARCHAR(255),
	CREATED_DATE VARCHAR(25),
	EXPIRED_DATE VARCHAR(25),
	FIRST_NAME VARCHAR(30),
	LAST_NAME VARCHAR(30),
	PHONE_NUMBER VARCHAR(20),
	UPDATE_DATE VARCHAR(30)
	);